baseURL = "https://<yourusername>.github.io/"
theme = "PaperMod"
title = "Sanjay Ramkumar"

[params]
  description = "Aerospace/robotics engineering portfolio"
  ShowReadingTime = true
  ShowShareButtons = false

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 10