baseURL = "https://sanjayramkumar27.github.io/"
title = "Sanjay Ramkumar"
theme = "PaperMod"

[params]
description = "Aerospace & Robotics Engineering Portfolio"
ShowReadingTime = true
ShowShareButtons = false

[menu]
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 10
  [[menu.main]]
    identifier = "competitions"
    name = "Competitions"
    url = "/competitions/"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Personal Projects"
    url = "/projects/"
    weight = 30